version: '3.8'

services:
  hostname: gesfrontend
  gesfrontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: "always"
    networks:
      bahmni-standard_default:
        aliases:
          - "bahmni_gn_frontend"
      
networks:
  bahmni-standard_default:
