version: '3.8'

services:
  gesfrontend:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: gesfrontend  
    ports:
      - "8092:8092"
    restart: "always"
    networks:
      bahmni-standard_default:
        aliases:
          - "gn_frontend-alias"
      
networks:
  bahmni-standard_default:
      aliases:
      - "gn_frontend-alias"
